---
title: "Corpus Co-occurrence Explorer"
output: 
  flexdashboard::flex_dashboard:
  orientation: columns
vertical_layout: fill
runtime: shiny
---
  
```{r setup, include=FALSE}
library(flexdashboard)
library(here)

ggplot2::theme_set(hrbrthemes::theme_ipsum())

load(here("data/results.rda"))

corpora <- list(
  "19th Century Novels" = "19C",
  "Jane Austen" = "austen",
  "Charles Dickens" = "DNov",
  "Thomas Hardy" = "hardy",
  "D. H. Lawrence" = "lawrence"
)

left_default <- "austen"
right_default <- "19C"
```

Inputs {.sidebar}
-----------------------------------------------------------------------
  
```{r}
selectInput(
  inputId = "left_corpus",
  label = h3("Left corpus"), 
  choices = corpora, 
  selected = left_default)
```

```{r}
selectInput(
  inputId = "right_corpus",
  label = h3("Right corpus"), 
  choices = corpora, 
  selected = right_default)
```

```{r}
radioButtons(
  inputId = "nodes",
  label = h3("Nodes"),
  choices = list(
    "Body parts (back, eye, eyes, forehead, hand, hands, head, shoulder)" = c('back', 'eye', 'eyes', 'forehead', 'hand', 'hands', 'head', 'shoulder')
  )
)
```

```{r}
sliderInput(
  inputId = "span",
  label = h3("Span"),
  min = -10, 
  max = 10,
  value = c(-5, 5)
)
```

```{r}
numericInput(
  inputId = "fdr",
  label = h3("False Discovery Rate"),
  min = 0.01,
  max = 1,
  step = 0.01,
  value = 0.01
)
```

Column {data-width=650}
-----------------------------------------------------------------------
  
### CoCo Plot
  
```{r}
library(tidyverse)

results_ <- reactive({
  results %>%
    filter(left == input$left_corpus) %>%
    filter(right == input$right_corpus) %>%
    arrange(x, effect_size) %>%
    mutate(n = row_number())
})
```

```{r, fig.height=10, fig.width=10}
library(plotly)

renderPlotly({
  results_() %>%
    ggplot(aes(reorder(paste(x, y), n), effect_size)) +
    geom_point(colour = "skyblue4") +
    geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper), colour = "seashell4") +
    coord_flip() +
    labs(
      x = "",
      y = "Effect size"
    ) +
    theme(
      panel.border = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.text.y  = element_text(family = "monospace")
    ) +
    geom_hline(yintercept = 0, colour = "grey", linetype = 2, size = 0.5) -> p
  ggplotly(p)
})
```

